---
title: "HW9 Q1"
output: html_document
---

```{r setup, include=FALSE}

install.packages('matlib')
library(matlib) 

knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

**Given**

L = 11.5 + 2w + 1.5c - 1.2o

L = $\beta_0$ + $\beta_1$w + $\beta_2$c + $\beta_3$h

**Putting into a system of equations:**

Solving for L where c = 1

15 = $\beta_0$ + $\beta_1$w + $\beta_2$c + 0

Solving for L where h = 1

13.5 = $\beta_0$ + $\beta_1$w + 0 + $\beta_3$h

Solving for L where o = 1

12.3 = $\beta_0$ + $\beta_1$w + 0 + 0

**Creating a matrix** form ax=b where x is the beta values

a =

```{=latex}
$
\begin{bmatrix}
1 & 1 & 0\\
1 & 0 & 1\\
1 & 0 & 0
\end{bmatrix}
$
```
x =

```{=tex}
\begin{bmatrix}
\beta_0 + \beta_1 w\\
\beta_2\\
\beta_3
\end{bmatrix}
```
b = x =

```{=tex}
\begin{bmatrix}
15\\
13.5\\
12.3
\end{bmatrix}
```
See below for solver

```{r}


w = 1

lifespan_orig <- function(animal){
  c = 0
  h = 0
  o = 0
  w = 1
  if (animal == "c") {
    c=1
  }
  else if (animal == "h") {
    h=1
  }
  else if (animal == "o") {
    o=1
  }
  L = 11.5+2*w+1.5*c-1.2*o
}

#Solved with w=1
L_o = lifespan_orig("o")
L_h = lifespan_orig("h")
L_c = lifespan_orig("c")


L_new  = B0  + B1 * w +  B2 * c +   0 * o + B3 * h

# Solving for different versions of L_new...
# B_0 is 10.3, B_1 is 2,  L_orig = 11.5 - 1.2
L_new (o=1) = 10.3 + 2 * w + 2.7 * 0 + 0 * 1 + 1.2 * 0    

# B_3 is 1.2, L_orig = 11.5
L_new (h=1) = 10.3 + 2 * w + 2.7 * 0 + 0 * 0 + 1.2 * 1 # o = 0, c = 0

# B_2 is 2.7.  L_orig = 11.5 + 1.5
L_new (c=1) = 10.3 + 2 * w + 2.7 * 1 + 0 * 0 + 1.2 * 0 # o = 0, h = 0
```