---
title: "HW9"
output: pdf_document
author: David Scaperoth
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
## install the package if it's not installed
## note: need to install libgit2-dev in terminal
##      >> apt-get update
##      >> apt-get install libgit2-dev
install.packages("remotes")
remotes::install_github("baumer-lab/fec16",force=TRUE)
# then select 1 for all updates
library(fec16)

library(ggplot2)
library(magrittr)
install.packages("gridExtra")
library(gridExtra)

install.packages('dplyr')
library(dplyr)

knitr::opts_chunk$set(echo = TRUE)
```

From previous Section...

```{r}
# Inner join based on the "cand_id" column
result <- inner_join(results_house, campaigns, by = "cand_id")
```

### Q3.4 Exploring - Indicator Variables and Scatter Plot

```{r create candidate party}
# OTHER category created from all ambiguous labels
result$candidate_party <- result$party
mask <- !(result$candidate_party=='REP' | result$candidate_party=='DEM')
result$candidate_party[mask] <- "OTHER"
```

```{r scatter plot, echo=TRUE, warning=FALSE, fig.height=4}

result %>%  
  ggplot() + 
  aes(x = ttl_disb, y = general_votes, color=candidate_party) +
  geom_point(stat = "identity") +
  ggtitle("Scatter Plot of\nCampaign Contributions vs. Votes in the House\n")+
  labs(x = "Campaign Contributions ($)", y="House Votes")+
  scale_y_continuous(labels = scales::comma)+
  scale_x_continuous(labels = scales::comma)+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(color = "Party")


```

### 
